### ISSUE TITLE
NameTagEdit - problem with packets

### ISSUE THREAD

**Issue by Utochk** [CyberdyneCC/Thermos#116]
[NameTagEdit](http://dev.bukkit.org/bukkit-plugins/nametagedit) doesn't work on KCauldron & Thermos servers. (I use Thermos b25, but tried to use this plugin on KCauldron 1.7.10-1614.175)

Problem is:

`Failed to send packet for player (Packet209SetScoreboardTeam) : 
java.lang.NullPointerException
at ca.wacos.nametagedit.PacketPlayOut.<init>(PacketPlayOut.java:79)
at ca.wacos.nametagedit.NametagManager.sendPacketsAddToTeam(NametagManager.java:464)
at ca.wacos.nametagedit.NametagManager.addToTeam(NametagManager.java:38)
at ca.wacos.nametagedit.NametagManager.update(NametagManager.java:165)
at ca.wacos.nametagedit.NametagCommand.setNametagSoft(NametagCommand.java:287)
at ca.wacos.nametagedit.NametagCommand.onCommand(NametagCommand.java:138)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181)
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717)
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1316)
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1098)
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:999)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:817)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675)
at java.lang.Thread.run(Thread.java:722)`

P.S.
It normally works on Spigot (1.7.10-SNAPSHOT-b1657)

**Comment by Yive** [comment]
What version of NametagEdit?

**Comment by spannerman79** [comment]
Perhaps from their CI - http://ci.playmc.cc/job/NametagEdit/lastStableBuild/ ?

**Comment by Utochk** [comment]
@Yive @spannerman79 
I tried all available NTE versions from 2.4.0 to 4.0 (dev.bukkit.org, spigotmc.org, Jenkins).

**Comment by Robotia** [comment]
@Utochk The version with the given crash log is not the latest. Please share the crash log from the latest version so I can better identify this problem.

**Comment by Utochk** [comment]
@Robotia 
NTE 4.0 crash log on Thermos b27 server after using [/ne command](http://i.imgur.com/MfizIxG.png):
`null
org.bukkit.command.CommandException: Unhandled exception executing command 'ne' in plugin NametagEdit v4.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.27]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.27]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1614.27]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1004) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:722) [?:1.7.0_05]
Caused by: java.lang.NullPointerException
	at mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:89) ~[?:?]
	at mkremins.fanciful.FancyMessage.<init>(FancyMessage.java:78) ~[?:?]
	at com.nametagedit.plugin.NametagCommand.sendUsage(NametagCommand.java:61) ~[?:?]
	at com.nametagedit.plugin.NametagCommand.onCommand(NametagCommand.java:33) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.27]
	... 13 more`

**Comment by Robotia** [comment]
@Utochk This type of error can be attributed to the originating plugin. This not due to Thermos.

Could you share the jar of the version that you were using earlier? Thanks!

**Comment by Utochk** [comment]
@Robotia 
[NametagEdit v2.4](http://dev.bukkit.org/bukkit-plugins/nametagedit/files/25-nametag-edit-v2-4/)

**Comment by Robotia** [comment]
Just looked through the code, it looks like NTE accesses classes in a manner similar to the Particle Effect Library. These sort of problems are very silly considering that the server will automatically remap imports. The makers of NTE thought that they need to custom-check the version and get the class themselves (which they don't).

Sorry, but I don't think this problem can be fixed in the near future :confused:
