### ISSUE TITLE
[Critical?] - Bukkit plugins throw errors and crash when use-real-names is set

### ISSUE THREAD

**Issue by DraksterAU** [CyberdyneCC/Thermos#148]
Sorry to be really annoying ... but the forge side of things is working from a planet name perspective (as in when I call the worlds name it comes back with the appropriate answer) but bukkit plugins just throw errors now.

Sample 1:

```
org.bukkit.command.CommandException: Unhandled exception executing command 'mw' in plugin MultiWorld v5.2.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.30]
        at me.incomprehendable.dev.pwp.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1614.30]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1004) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at multiworld.command.world.InfoCommand.runCommand(InfoCommand.java:68) ~[?:?]
        at multiworld.command.Command.excute(Command.java:55) ~[?:?]
        at multiworld.command.CommandMap.parseCommand(CommandMap.java:37) ~[?:?]
        at multiworld.command.CommandMap.runCommand(CommandMap.java:67) ~[?:?]
        at multiworld.command.Command.excute(Command.java:55) ~[?:?]
        at multiworld.MultiWorldPlugin.pushCommandStack(MultiWorldPlugin.java:221) ~[?:?]
        at multiworld.MultiWorldPlugin.onCommand(MultiWorldPlugin.java:206) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.30]
        ... 13 more

Sample 2:

Could not pass event PlayerMoveEvent to Inquisitor v2.28
org.bukkit.event.EventException
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:118) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.30]
        at me.incomprehendable.dev.pwp.transparentlisteners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:28) [PerWorldPlugins.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.30]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.30]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:361) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1004) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:822) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:675) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
        at com.frdfsnlght.inquisitor.PlayerStats.onPlayerMove(PlayerStats.java:513) ~[?:?]
        at com.frdfsnlght.inquisitor.PlayerListenerImpl.onPlayerMove(PlayerListenerImpl.java:99) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor158.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_66]
        at me.incomprehendable.dev.pwp.transparentlisteners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:116) ~[?:?]
        ... 14 more
```

**Comment by DraksterAU** [comment]
Note - The forge side of Themos was also affected. The real names setting fixes this... so perhaps there is just something missing for bukkit.

**Comment by DraksterAU** [comment]
@Robotia I think this is because the world save directory is mapped to the same name in bukkit.... possibly? Youll need to cater for that on the bukkit side if they differ?

**Comment by Robotia** [comment]
The save directory is still DIM##, which is probably part of the problem :/

**Comment by DraksterAU** [comment]
I don't know how thermos works but can you, from the Bukkit side, translate the name into the dim folder whenever it is referenced?

**Comment by DraksterAU** [comment]
Even better, when this setting is enabled.... Allow the world folders to be created as the name... And allow us to migrate worlds manually.

For new installs this will have no consequence...?

**Comment by DraksterAU** [comment]
Starting to see why blood didn't think it was worth it... But if you finish this it closes off an old as hell bug haha

**Comment by DraksterAU** [comment]
@robotia for now if I Symlink the directories would that work?

**Comment by Robotia** [comment]
Not sure, I wouldn't recommend that

**Comment by DraksterAU** [comment]
Ok I'll leave it to the expert :)

**Comment by spannerman79** [comment]
In theory sym linking would work only if java can follow a sym link properly and if the plugins that you use @DraksterAU follow sym links correctly. Most plugins I've noticed have been done by kids so I wouldn't hold my breath in hope...

**Comment by DraksterAU** [comment]
@spannerman79 Hence my I'll leave it to the expert comment lol

**Comment by DraksterAU** [comment]
@Robotia Think you're going to be able to finish this man? :) (Not hurrying u up.. just wondering if u plan on it haha)

**Comment by Robotia** [comment]
I do, not sure how soon though

**Comment by Robotia** [comment]
Real names are not going to be supported.
