### ISSUE TITLE
Thermos Security Manager doesn't allow redis

### ISSUE THREAD

**Issue by Time6628** [CyberdyneCC/Thermos#254]
```
[15:04:05] [Server thread/ERROR]: Error occurred while enabling GlobalMarket v2.0.0.21 (Is it up to date?)
java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
    at java.security.AccessControlContext.checkPermission(AccessControlContext.java:457) ~[?:1.8.0_05]
    at java.lang.SecurityManager.checkPermission(SecurityManager.java:585) ~[?:1.8.0_05]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848) ~[?:1.8.0_05]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322) ~[?:1.8.0_05]
    at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_05]
    at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxRegister(BaseGenericObjectPool.java:957) ~[?:?]
    at org.apache.commons.pool2.impl.BaseGenericObjectPool.<init>(BaseGenericObjectPool.java:133) ~[?:?]
    at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:107) ~[?:?]
    at lib.jedis.util.Pool.initPool(Pool.java:43) ~[?:?]
    at lib.jedis.util.Pool.<init>(Pool.java:31) ~[?:?]
    at lib.jedis.jedis.JedisPool.<init>(JedisPool.java:73) ~[?:?]
    at lib.jedis.jedis.JedisPool.<init>(JedisPool.java:54) ~[?:?]
    at me.dasfaust.gm.storage.RedisStorage.init(RedisStorage.java:67) ~[?:?]
    at me.dasfaust.gm.Core.onEnable(Core.java:71) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.25]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.25]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.25]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:1.7.10-1614.25]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:1.7.10-1614.25]
    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:512) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:486) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:446) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_05]
```

The dev of GlobalMarket said it was something to do with thermos' security manager. (https://github.com/Dasfaust/GlobalMarket/issues/80)

Occurs on the latest Thermos 50 build as well as anything between 18 and 49.

**Comment by iKaneki-Ken** [comment]
This isn't a Thermos issue, this is a security policy issue inside Java's files.

**Comment by Time6628** [comment]
@iKaneki-Ken I have it in the java security file.

**Comment by Robotia** [comment]
Which file are you using? I have looked but cannot find anything about Thermos editing the security policy.

You should've added a line like this:
`permission javax.management.MBeanTrustPermission "register";`
in `$JAVA_HOME/lib/security/java.policy` ( `/usr/lib/jvm/java-8-oracle/jre/lib/security/java.policy` for Oracle Java 8 Users)

**Comment by Robotia** [comment]
Whoops...I think I've just found it, pushing something which *should* resolve it.

**Comment by Time6628** [comment]
Just built the latest version and it appears that the commit that fixes this breaks thermos entirely xD.
Every time I try to startup the server:
```
30.03 20:20:48 [Server] INFO We appear to be missing one or more essential library files.
30.03 20:20:48 [Server] INFO You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
30.03 20:20:48 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
30.03 20:20:48 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
30.03 20:20:48 [Server] INFO at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
30.03 20:20:48 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
30.03 20:20:48 [Server] INFO at java.lang.Class.forName0(Native Method)
30.03 20:20:48 [Server] INFO at java.lang.Class.forName(Class.java:348)
30.03 20:20:48 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25)
30.03 20:20:48 [Server] INFO at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)
```
And before someone says that I have the libraries installed incorrectly, the launchwrapper is in the libraries/net/minecraft/launchwrapper/1.12 folder :P

**Comment by Time6628** [comment]
Getting this crash when I startup the server https://gist.github.com/Time6628/843ce172a3db05579fc00dd25bac6636

**Comment by Rubbertjuh** [comment]
Running build 57 and still having issues with Redis not having permission.
I'm trying to set up ExecuteEverywhere, here's my log:
http://hastebin.com/odegabuweg.avrasm

**Comment by spannerman79** [comment]
@Rubbertjuh add `-Djava.security.policy=server.policy` to your launch options with `server.policy` containing the following;

```
grant {
   permission javax.management.MBeanTrustPermission "register";
};
```

**Comment by Time6628** [comment]
@spannerman79 that's the problem, the permission doesn't work like it should.

**Comment by Rubbertjuh** [comment]
@spannerman79 Thanks a lot, for now, this seems to have fixed the problem =D Cheers! 
I edited the Java.policy file in the java directory.
I didn't even have to add the flar to my launch options!
