### ISSUE TITLE
Erebus - Already decorating crash

### ISSUE THREAD

**Issue by Killgrave** [CyberdyneCC/Thermos#294]
```
java.lang.RuntimeException: Already decorating Erebus!
	at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:37)
	at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
	at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:766)
	at net.minecraft.world.World.func_147439_a(World.java:692)
	at net.minecraft.world.World.func_98179_a(World.java:3675)
	at net.minecraft.world.World.updateLightByType(World.java:3806)
	at net.minecraft.world.World.func_147463_c(World.java:4879)
	at net.minecraft.world.World.func_147451_t(World.java:3663)
	at net.minecraft.world.World.func_147465_d(World.java:842)
	at net.minecraft.world.World.func_147449_b(World.java:996)
	at erebus.world.feature.decoration.WorldGenRedGem.func_76484_a(WorldGenRedGem.java:34)
	at erebus.world.biomes.decorators.BiomeDecoratorSubmergedSwamp.generateFeature(BiomeDecoratorSubmergedSwamp.java:272)
	at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:45)
	at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
	at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:766)
	at net.minecraft.world.World.func_147439_a(World.java:692)
	at erebus.world.SpawnerErebus.runGradualSpawning(SpawnerErebus.java:160)
	at erebus.world.SpawnerErebus.onServerTick(SpawnerErebus.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_97_SpawnerErebus_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
```
```
java.lang.RuntimeException: Already decorating Erebus!
	at erebus.world.biomes.decorators.BiomeDecoratorBaseErebus.decorate(BiomeDecoratorBaseErebus.java:37)
	at erebus.world.biomes.BiomeBaseErebus.func_76728_a(BiomeBaseErebus.java:111)
	at erebus.world.ChunkProviderErebus.func_73153_a(ChunkProviderErebus.java:399)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1191)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:907)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
	at java.lang.Thread.run(Thread.java:745)
```

Erebus 0.4.5
Thermos 44
Forge 1614

**Comment by linkinkov** [comment]
Maybe update to the last build?
In change list it was fixed a long time ago

**Comment by Killgrave** [comment]
where links für downloaden ?

**Comment by Robotia** [comment]
This isn't caused by Thermos from what I can tell... erebus mod is at fault. This issue was already fixed for regular world generators.

**Comment by Killgrave** [comment]
gut i trued last download an get cresh agein. was i not get dis on sigle player?

**Comment by Robotia** [comment]
Es zeichnet sich durch, dass nicht Thermos verursacht

**Comment by Robotia** [comment]
Try disable async lighting in `spigot.yml`

**Comment by Robotia** [comment]
No response for 13 days, issue is caused by the mod's chunk generator.

**Comment by aetherpirate** [comment]
I am in a similar boat, same error

Erebus 1.4.7
Thermos 57 1614

Project Ozone 2 (2.1.8), Titan Mode. 

Also get the "Already Decorating" error when players explore in The Erebus. 
I tried disabling async lighting in spigot.yml, error still happens with same frequency. 

Is there any new information about this error? If there is any additional useful info I can provide, please let me know.

**Comment by Eufranio** [comment]
@aetherpirate Build 58 has some worldgen fixes, try using this build. 
(https://github.com/CyberdyneCC/Thermos/releases/tag/58)

**Comment by aetherpirate** [comment]
Thanks, I will test with that. Have any fixes been applied to that build in the past couple months? I've tried it with other packs and found it to be problematic.

**Comment by Eufranio** [comment]
I don't think so, but I don't have problems with it.

**Comment by cubespace** [comment]
I have the same problem. In the beginning of the topic, crash servers.

**Comment by Time6628** [comment]
Issue is caused by the erebus mod.
