### ISSUE TITLE
bungeecord problem  can't  connect kcauldron & Thermos server

### ISSUE THREAD

**Issue by caizhong3** [CyberdyneCC/Thermos#355]
bungeecord problem player  can't  connect kcauldron & Thermos server
but spigot is normal  

[严重] [PorPit] <-> DownstreamBridge <-> [mod] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by JewishDog** [comment]
Использовать bungeecord с forge'м не очень хорошая идея..
И если что, то bungeecord хорошо работает с kcauldon'ом и Thermos'ом.
Если у тебя какие-то проблемы, то ты предоставь логи и прочую информацию.

**Comment by iKaneki-Ken** [comment]
You'll need to tell us if you have your servers set to offline mode or not, as well, please post your BungeeCord config.

**Comment by caizhong3** [comment]
[严重] [PorPit] <-> DownstreamBridge <-> [mod] - encountered exception
io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by caizhong3** [comment]
config 


ip_forward: true
network_compression_threshold: 256
stats: e1e16da7-a6eb-474e-ad0e-2b3e407c4a61
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
permissions:
  default: null
  admin: null
groups: {}
servers:
  登录服:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
  模组生存1服:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25567
    restricted: false
  纯净生存1服:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25570
    restricted: false
  模组空岛服:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25580
    restricted: false
  神奇宝贝服:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25590
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
  priorities:
  - 登录服
  - 登录服
  default_server: 登录服
  fallback_server: 登录服
player_limit: -1
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000

**Comment by JewishDog** [comment]
попробуй вот этот прокси сервер.
http://rubukkit.org/threads/golilypad-proksi-server-dlja-serverov-minecraft.121373/

**Comment by iKaneki-Ken** [comment]
You're using the wrong version of BungeeCord. Use this one:

http://gogs.tcpr.ca/TCPR/Fixes/src/master/BungeeCord

**Comment by Xuwznln** [comment]
So....What's your qq number?用那个修复版的bungeecord试试
