### ISSUE TITLE
Plugin issue - problem sometimes preparing configs.

### ISSUE THREAD

**Issue by Tencao** [CyberdyneCC/Thermos#359]
This issue has only been experienced with one plugin so far, and from what the devs have said, seems like a cauldron specific issue. When setting up the plugin, **uSkyBlock**, one of the configs seems to copy a bit weirdly. The plugin copied challenges.yml, which it immediately deemed unreadable due to special characters.
`[12:57:23] [Server thread/ERROR]: Unable to read config file plugins\uSkyBlock\challenges.yml org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xFFFD) special characters are not allowed in "<string>", position 3077 at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[YamlConfiguration.class:1.7.10-1614.56] at us.talabrek.ultimateskyblock.utils.yml.YmlConfiguration.loadFromString(YmlConfiguration.java:31) ~[?:?] at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[FileConfiguration.class:1.7.10-1614.56] at us.talabrek.ultimateskyblock.utils.file.FileUtil.readConfig(FileUtil.java:61) [uSkyBlock.jar:?] at us.talabrek.ultimateskyblock.utils.file.FileUtil.getYmlConfiguration(FileUtil.java:138) [uSkyBlock.jar:?] at us.talabrek.ultimateskyblock.uSkyBlock.reloadConfigs(uSkyBlock.java:1154) [uSkyBlock.jar:?] at us.talabrek.ultimateskyblock.uSkyBlock.onEnable(uSkyBlock.java:216) [uSkyBlock.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [JavaPlugin.class:1.7.10-1614.56] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.56] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.56] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.56] at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.56] at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?] at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?] at net.minecraft.world.World.<init>(World.java:371) [ahb.class:?] at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_73] Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70) ~[StreamReader.class:?] at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50) ~[StreamReader.class:?] at org.yaml.snakeyaml.Yaml.load(Yaml.java:399) ~[Yaml.class:?] at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[YamlConfiguration.class:1.7.10-1614.56] ... 19 more [12:57:23] [Server thread/INFO]: Moving existing config challenges.yml to backup/challenges-20160514-1257.yml`

Here is the pastebin of the config output
http://pastebin.com/8Tuv8g3k

After going through it, and eventually manually copying the config out of the plugin itself, it ended up perfectly working, so I decided to compare the fully working one with the broken one, and found this difference.

Corrupted
`challengeColor: "\xa7e"`

Working
`challengeColor: '§e'`

This could be an issue with Thermos copying that symbol over, so I'm leaving this here in hopes it can be tested more, and hopefully fixed.

**Comment by Time6628** [comment]
So why not just use the `§e` character instead?

**Comment by Tencao** [comment]
I'll have a look into that, but what I mean is, automatically as the plugin was setup, Thermos could not copy that character, yet the plugin required it to read the color code correctly. I tried to ask the plugin devs first if it was an issue with their plugin, however they were very adamant it wasn't their plugin causing it, so I came here to see if it's a problem with Thermos copying the character.

**Comment by Time6628** [comment]
I think it's probably because the default config doesn't have '' around it... not sure, but that's what I think xD https://github.com/rlf/uSkyBlock/blob/master/uSkyBlock-Core/src/main/resources/challenges.yml#L25.
