### ISSUE TITLE
Stopping the operation of devices

### ISSUE THREAD

**Issue by DrLeonardo** [CyberdyneCC/Thermos#384]
**Server Error/Warns:** [Pastebin](http://pastebin.com/gZgFyz6b)
**Server Log:** [Pastebin](http://pastebin.com/5k2ac7sV)

**Explanation of issue:** 
After a planned restart , suddenly all devices (IC2, AE2, CarpenterBlocks (garagedoor), EnderChest etc.) and other devices stopped , while in the server console began to appear strange error :

` [Server] INFO at crazypants.enderio.conduit.AbstractConduitNetwork.setNetwork(AbstractConduitNetwork.java:49) [AbstractConduitNetwork.class:?]

 [Server] INFO at crazypants.enderio.conduit.redstone.RedstoneConduitNetwork.notifyConduitNeighbours(RedstoneConduitNetwork.java:201) [RedstoneConduitNetwork.class:?]

[Server] INFO at openmods.block.OpenBlock.func_149695_a(OpenBlock.java:331) [OpenBlock.class:?]

[Server] INFO at net.minecraft.world.World.func_147460_e(World.java:1144) [ahb.class:?]

[Server] INFO at net.minecraftforge.common.ForgeHooks.onPlayerTossEvent(ForgeHooks.java:366) [ForgeHooks.class:1.7.10-1614.56]`

after the forced restart problem corrected itself, but sometimes the device is stopped for no apparent reason.

Please understand the problem

**Mods Installed:** appliedenergistics2-core, CodeChickenCore, itemphysic, NotEnoughItems, PotionExtensionCore, ThE-core, ThaumicTinkerer-preloader, OpenModsCore, <CoFH ASM>, BinniePatcher, AdvancedSolarPanel, ae2stuff, appliedenergistics2, atum, BiblioCraft, Botany, BinnieCore, ExtraBees, ExtraTrees, Genetics, BiomesOPlenty, BiomeTweaker, Botania, BuildCraft|Builders, BuildCraft|Transport, BuildCraft|Energy, BuildCraft|Silicon, BuildCraft|Robotics, BuildCraft|Core, BuildCraft|Factory, BiblioWoodsBoP, BiblioWoodsForestry, CarpentersBlocks, chisel, customnpcs, DragonsRadioMod, BrandonsCore, DraconicEvolution, EMT, EnderIO, extracells, ExtraTiC, ExtraUtilities, ForbiddenMagic, Forestry, MCFrames, ForgeRelocation, RelocationFMP, GraviSuite, HardcoreEnderExpansion, harvestcraft, IC2CA, IC2NuclearControl, IC2, IronChest, JABBA, MagicBees, malisisdoors, OpenBlocks, PowerUtils, ProjectBlue, ProjRed|Core, ProjRed|Compatibility, ProjRed|Integration, ProjRed|Transmission, ProjRed|Illumination, Railcraft, RTG, AS_Ruins, TConstruct, Thaumcraft, thaumicenergistics, ThaumicExploration, ThaumicHorizons, ThaumicTinkerer, ThermalDynamics, ThermalExpansion, ThermalFoundation, TiCTooltips, TwilightForest, wildcaves3, witchery, aobd, Baubles, bdlib, CoFHCore, endercore, EventHelper, fc-dummy, fastleafdecay, ForgeMicroblock, ForgeMultipart, McMultipart, HoloInventory, malisiscore, Mantle, MineTweaker3, modtweaker2, MrTJPCoreMod, NEIAddons|Developer, NEIAddons|AppEng, NEIAddons|Botany, NEIAddons|Forestry, NEIAddons|CraftingTables, NEIAddons, NEIAddons|ExNihilo, recipemod, netherportalfix, OpenMods, qreport-server, forge-vault, thaumcraftneiplugin, TickProfiler] at CLIENT

**Thermos Version:** Thermos-1.7.10-1614-56.zip

**Forge Version:** 1.7.10-1614

**Comment by Time6628** [comment]
Please provide logs using [pastebin](http://pastebin.com/), [hastebin](http://hastebin.com/), or [gist.github.com](https://gist.github.com/).

**Comment by DrLeonardo** [comment]
server logs
[fml-server-1.zip](https://github.com/CyberdyneCC/Thermos/files/298514/fml-server-1.zip)

**Comment by Time6628** [comment]
Can you put them on one of the links I provided above? Makes it easier for everyone to read em instead of downloading them.

**Comment by Time6628** [comment]
Ah I see. Timeismoney is not handling the FakePlayers of the machines correctly.

**Comment by DrLeonardo** [comment]
My problem is similar to the [https://github.com/CyberdyneCC/Thermos/issues/388](url)

> Ah I see

I could not attach logs to the services that you provide , the file size is too large

Now on the server, I had another complaint about the disappearance of items from the Chest.

Chest of vanilla minecraft, it was 6 stacks of stone and bees of Forestry, after a chunk reload, the entire stone has disappeared and the bees that were put there yesterday were there.

what could be the problem?
The logs do not have any errors or warn messages.

**Comment by Time6628** [comment]
Try build 55.
