### ISSUE TITLE
Player.spigot() particle effect method not implemented

### ISSUE THREAD

**Issue by AipaMC** [CyberdyneCC/Thermos#454]
**Explanation of issue:**
The method in the Player.Spigot class playEffect() is not overridden in the CraftPlayer implementation. Therefore plugins trying to use that throw UnsupportedException errors in console:
Ex:
`[22:59:12] [Server thread/WARN]: [KandorusSimpleQuest] Task #13 for KandorusSimpleQuest v1.0 generated an exception
java.lang.UnsupportedOperationException: Not supported yet.
	at org.bukkit.entity.Player$Spigot.playEffect(Player.java:1048) ~[Player$Spigot.class:1.7.10-1614.57]
	at com.kandorus.simplequest.QuestParticleSystem.run(QuestParticleSystem.java:38) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71) ~[CraftTask.class:1.7.10-1614.57]
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346) [CraftScheduler.class:1.7.10-1614.57]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:905) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]`

Version:
1.7.10-R0.1-SNAPSHOT | 1.7.10-1614.57 (MC: 1.7.10)

**Comment by Time6628** [comment]
It's because the method is actually not supported.

**Comment by AipaMC** [comment]
But why not? It's implemented in CraftWorld?
https://github.com/CyberdyneCC/Thermos/blob/master/src/main/java/org/bukkit/craftbukkit/CraftWorld.java

**Comment by Time6628** [comment]
And why can't you just use that?

**Comment by AipaMC** [comment]
That one plays for the entire server (or those in range). The one specific to the Player class only plays for one player.
