### ISSUE TITLE
(ISSUES)

### ISSUE THREAD

**Issue by Sephiroth234** [CyberdyneCC/Thermos#462]
[16:36:24] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[16:36:24] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[16:36:24] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[16:36:24] [main/INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[16:36:25] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_101, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_101
[16:36:25] [main/INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[16:36:25] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:25] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:36:25] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:25] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[16:36:25] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:36:26] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:36:26] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[16:36:26] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[16:36:26] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[16:36:26] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[16:36:27] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[16:36:31] [Server thread/INFO]: Starting minecraft server version 1.7.10
[16:36:31] [Server thread/INFO]: Attempting early MinecraftForge initialization
[16:36:31] [Server thread/INFO]: MinecraftForge v10.13.4.1614 Initialized
[16:36:31] [Server thread/INFO]: Replaced 184 ore recipies
[16:36:31] [Server thread/INFO]: Completed early MinecraftForge initialization
[16:36:31] [Server thread/INFO]: Config directory created successfully
[16:36:31] [Server thread/INFO]: Found 0 mods from the command line. Injecting into mod discoverer
[16:36:31] [Server thread/INFO]: Searching C:\Users\Diabl\Desktop\The Last Days - Server\mods for mods
[16:36:32] [Server thread/INFO]: Forge Mod Loader has identified 4 mods to load
[16:36:32] [Server thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, kimagine] at CLIENT
[16:36:32] [Server thread/INFO]: Attempting connection with missing mods [mcp, FML, Forge, kimagine] at SERVER
[16:36:32] [Server thread/INFO]: Processing ObjectHolder annotations
[16:36:32] [Server thread/INFO]: Found 341 ObjectHolder annotations
[16:36:32] [Server thread/INFO]: Identifying ItemStackHolder annotations
[16:36:32] [Server thread/INFO]: Found 0 ItemStackHolder annotations
[16:36:32] [Server thread/INFO]: Configured a dormant chunk cache size of 0
[16:36:32] [Server thread/INFO]: Applying holder lookups
[16:36:32] [Server thread/INFO]: Holder lookups applied
[16:36:32] [Server thread/INFO]: Injecting itemstacks
[16:36:32] [Server thread/INFO]: Itemstack injection complete
[16:36:32] [Server thread/INFO]: Loading properties
[16:36:32] [Server thread/WARN]: server.properties does not exist
[16:36:32] [Server thread/INFO]: Generating new properties file
[16:36:32] [Server thread/INFO]: Default game type: SURVIVAL
[16:36:33] [Server thread/INFO]: This server is running Cauldron version 1.7.10-1614.57 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[16:36:33] [Server thread/WARN]: Failed to load user banlist: 
java.io.FileNotFoundException: banned-players.json (Le fichier spécifié est introuvable)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_101]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_101]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.io.Files.newReader(Files.java:86) ~[server-1.7.10.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(UserList.java:201) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_152620_y(SourceFile:99) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:25) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:235) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[16:36:33] [Server thread/WARN]: Failed to load ip banlist: 
java.io.FileNotFoundException: banned-ips.json (Le fichier spécifié est introuvable)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_101]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_101]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.io.Files.newReader(Files.java:86) ~[server-1.7.10.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(UserList.java:201) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_152619_x(SourceFile:91) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:27) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:235) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[16:36:33] [Server thread/WARN]: Failed to load operators list: 
java.io.FileNotFoundException: ops.json (Le fichier spécifié est introuvable)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_101]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_101]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.io.Files.newReader(Files.java:86) ~[server-1.7.10.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(UserList.java:201) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_72417_t(SourceFile:107) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:29) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:235) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[16:36:33] [Server thread/WARN]: Failed to load white-list: 
java.io.FileNotFoundException: whitelist.json (Le fichier spécifié est introuvable)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_101]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_101]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_101]
	at com.google.common.io.Files.newReader(Files.java:86) ~[server-1.7.10.jar:?]
	at net.minecraft.server.management.UserList.func_152679_g(UserList.java:201) ~[om.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.func_72418_v(SourceFile:123) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedPlayerList.<init>(SourceFile:30) [ls.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:235) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
[16:36:33] [Server thread/INFO]: Server Ping Player Sample Count: 12
[16:36:33] [Server thread/INFO]: Using 4 threads for Netty based IO
[16:36:33] [Server thread/INFO]: Generating keypair
[16:36:33] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:36:33] [Server thread/INFO]: Injecting itemstacks
[16:36:33] [Server thread/INFO]: Itemstack injection complete
[16:36:33] [Server thread/INFO]: Forge Mod Loader has successfully loaded 4 mods
[16:36:33] [Server thread/INFO]: Preparing level "world"
[16:36:33] [Server thread/INFO]: Registered command debug with permission node vanilla.command.debug
[16:36:33] [Server thread/INFO]: Registered command spreadplayers with permission node vanilla.command.spreadplayers
[16:36:33] [Server thread/INFO]: Registered command playsound with permission node vanilla.command.playsound
[16:36:33] [Server thread/INFO]: Registered command scoreboard with permission node vanilla.command.scoreboard
[16:36:33] [Server thread/INFO]: Registered command achievement with permission node vanilla.command.achievement
[16:36:33] [Server thread/INFO]: Registered command summon with permission node vanilla.command.summon
[16:36:33] [Server thread/INFO]: Registered command setblock with permission node vanilla.command.setblock
[16:36:33] [Server thread/INFO]: Registered command testforblock with permission node vanilla.command.testforblock
[16:36:33] [Server thread/INFO]: Registered command tellraw with permission node vanilla.command.tellraw
[16:36:33] [Server thread/INFO]: Registered command netstat with permission node vanilla.command.netstat
[16:36:34] [Server thread/INFO]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@3ed47314)
[16:36:34] [Server thread/INFO]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@3ed47314)
[16:36:34] [Server thread/INFO]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@3ed47314)
[16:36:34] [Server thread/INFO]: Preparing start region for level 0
[16:36:35] [Server thread/INFO]: Preparing spawn area: 11%
[16:36:36] [Server thread/INFO]: Preparing spawn area: 38%
[16:36:37] [Server thread/INFO]: Preparing spawn area: 65%
[16:36:38] [Server thread/INFO]: Preparing spawn area: 93%
[16:36:39] [Server thread/INFO]: Done (5,091s)! For help, type "help" or "?"
[16:36:39] [Server thread/INFO]: Registered command forge with permission node net.minecraftforge.server.command.ForgeCommand
[16:36:39] [Server thread/INFO]: Hey, you don't have a server icon! Try out one of Thermos' Icon Generators at https://github.com/CyberdyneCC/ThermosIconGenerators !
[16:36:39] [Server thread/INFO]: [Thermos] Refusing to lock affinity, disabled in cauldron.yml
[16:36:40] [Thermos version retriever/WARN]: Error occured during retriving version
java.lang.Throwable
	at thermos.TLog.log(TLog.java:30) [TLog.class:1.7.10-1614.57]
	at thermos.TLog.warning(TLog.java:41) [TLog.class:1.7.10-1614.57]
	at thermos.updater.TVersionRetriever.uncaughtException(TVersionRetriever.java:111) [TVersionRetriever.class:1.7.10-1614.57]
	at thermos.updater.TVersionRetriever.check(TVersionRetriever.java:91) [TVersionRetriever.class:1.7.10-1614.57]
	at thermos.updater.TVersionRetriever.run(TVersionRetriever.java:69) [TVersionRetriever.class:1.7.10-1614.57]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.IllegalStateException: Status code isn't OK
	... 3 more
#

**Comment by iKaneki-Ken** [comment]
I see no issues with your startup log.

**Comment by Time6628** [comment]
Follow the template please.

**Comment by Sephiroth234** [comment]
Thanks x)
