### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ASuperthings** [CyberdyneCC/Thermos#511]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 9/2/16 10:39 PM
Description: Exception ticking world

java.lang.RuntimeException: DISPATCHER expects a NetworkDispatcher
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$2.validateArgs(FMLOutboundHandler.java:59)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:263)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at cpw.mods.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:48)
	at WayofTime.alchemicalWizardry.common.NewPacketHandler.getPacket(NewPacketHandler.java:984)
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145844_m(TEAltar.java:668)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:629)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:571)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:84)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$2.validateArgs(FMLOutboundHandler.java:59)
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:263)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637)
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:626)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:878)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:229)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:195)
	at cpw.mods.fml.common.network.FMLEmbeddedChannel.generatePacketFrom(FMLEmbeddedChannel.java:48)
	at WayofTime.alchemicalWizardry.common.NewPacketHandler.getPacket(NewPacketHandler.java:984)
	at WayofTime.alchemicalWizardry.common.tileEntity.TEAltar.func_145844_m(TEAltar.java:668)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_151252_a(PlayerManager.java:629)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.func_73254_a(PlayerManager.java:571)
	at net.minecraft.server.management.PlayerManager.func_72693_b(PlayerManager.java:84)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:291)

-- Affected level --
Details:
	Level name: plotworld
	All players: 19 total; [EntityPlayerMP['qing_feng'/3013366, l='plotworld', x=-300.39, y=58.69, z=228.32](qing_feng at -300.3926300640654,58.6875,228.31762709799955), EntityPlayerMP['Alager'/3094781, l='plotworld', x=-218.16, y=67.70, z=975.26](Alager at -218.1564680061716,67.70362554998225,975.25846979623), EntityPlayerMP['Doce_qi'/2991033, l='plotworld', x=-460.56, y=71.00, z=106.53](Doce_qi at -460.55756980337134,71.0,106.53327542467115), EntityPlayerMP['foon'/3124042, l='plotworld', x=-169.60, y=65.00, z=-670.26](foon at -169.60373261411195,65.0,-670.2617002449725), EntityPlayerMP['H_Herobrine'/3219602, l='plotworld', x=452.60, y=65.00, z=181.42](H_Herobrine at 452.59954919448666,65.0,181.42183258466665), EntityPlayerMP['jingyu'/3280672, l='plotworld', x=-460.32, y=71.00, z=108.30](jingyu at -460.32184365397245,71.0,108.30000001192093), EntityPlayerMP['MC_Lm'/3331926, l='plotworld', x=-77.15, y=65.00, z=-644.92](MC_Lm at -77.146944870039,65.0,-644.919857452395), EntityPlayerMP['wangling'/3359683, l='plotworld', x=-161.83, y=65.00, z=293.93](wangling at -161.83448723165202,65.0,293.9304380256141), EntityPlayerMP['tcdwyut'/3379224, l='plotworld', x=337.59, y=66.00, z=-438.93](tcdwyut at 337.593518327868,66.0,-438.93328107322435), EntityPlayerMP['XUE_BiB'/3011960, l='plotworld', x=381.64, y=65.00, z=-62.91](XUE_BiB at 381.6373411378715,65.0,-62.90877173502692), EntityPlayerMP['jadbaj'/2984153, l='plotworld', x=171.84, y=65.00, z=-473.65](jadbaj at 171.84435997828572,65.0,-473.6491057598298), EntityPlayerMP['bai'/3377144, l='plotworld', x=-15.76, y=65.00, z=-631.86](bai at -15.75904180544362,65.0,-631.8624643716087), EntityPlayerMP['hexieDD'/3319936, l='plotworld', x=-172.05, y=65.00, z=293.32](hexieDD at -172.0540281966109,65.0,293.322123285703), EntityPlayerMP['bimada'/2985168, l='plotworld', x=-224.72, y=65.00, z=-189.43](bimada at -224.72058740852887,65.0,-189.4281971185294), EntityPlayerMP['wui_yun'/3371586, l='plotworld', x=222.05, y=66.00, z=6.05](wui_yun at 222.04587487693522,66.0,6.050918466870932), EntityPlayerMP['GSD__WeiAi'/3058204, l='plotworld', x=137.33, y=67.25, z=-508.38](GSD__WeiAi at 137.33266702080994,67.24918707874468,-508.37600045425654), EntityPlayerMP['AldnoahLink'/3447323, l='plotworld', x=-310.42, y=65.00, z=89.86](AldnoahLink at -310.41949820131055,65.0,89.85847067593161), EntityPlayerMP['laohentai'/3044782, l='plotworld', x=295.67, y=65.00, z=-120.63](laohentai at 295.6682231860085,65.0,-120.63405539263292), EntityPlayerMP['GB_HH'/3286324, l='plotworld', x=398.24, y=65.60, z=358.60](GB_HH at 398.24373102724934,65.60408037809304,358.60258747239084)]
	Chunk stats: ServerChunkCache: 1652 Drop: 0
	Level seed: -1868264538500949831
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-61,65,53), Chunk: (at 3,4,5 in -4,3; contains blocks -64,0,48 to -49,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 18497426 game time, 18694001 day time
	Level dimension: 3
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 114652 (now: false), thunder time: 64179 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cyberdynecc:Thermos:1.7.10-1614.58
	Plugins: CoreProtect, WorldEdit, Essentials, GroupManager, PlaceholderAPI, AutoMessage, AutoShutdown, NPT, NoBreak-Ms, WorldBorder, LaggRemover, ProtocolLib, EasyKits, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, BanItem, AT, LWCField, mcMMO, AutoSave, BossShop, Vault, EssentialsSpawn, WTP, GemPro, ScoreboardStats, NeverLag, PlotSquared, LWC, QuickShop, Marriage, Multiverse-Core, Residence, UltimateGuild, ServerSigns, RandomLocation, Mcrmb, ResExtras, MyPet, RPG_Items, AuthMe, HolographicDisplays, IntensifyRL, McrmbShop, McrmbVip
	Disabled Plugins: 
	Operating System: Linux (amd64) version 3.10.85-1.el6.elrepo.x86_64
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3443729024 bytes (3284 MB) / 5221384192 bytes (4979 MB) up to 5221384192 bytes (4979 MB)
	JVM Flags: 6 total; -XX:+UseFastAccessorMethods -XX:+UseParallelGC -XX:ParallelGCThreads=8 -XX:MaxDirectMemorySize=540M -XX:MaxMetaspaceSize=448M -Xmx5156M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (Thermos-1.7.10-1614.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (Thermos-1.7.10-1614.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	balumg{1.0.0} [balumg] ([巴鲁蒙格]Balmung 1.7.10.jar) 
	UCHIJAAAA	mod_ecru_MapleTree{1.1.32c} [MapleTree] ([枫树]MapleTree Forgev1.1.32c.jar) 
	UCHIJAAAA	flammpfeil.slashblade{mc1.7.10-r86} [SlashBlade] (SlashBlade-mc1.7.10-r86.jar) 
	UCHIJAAAA	flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] ([神剑]SlashBlade-Kamuy-mc1.7.10-r6.jar) 
	UCHIJAAAA	IC2{2.2.824-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.824-experimental.jar) 
	UCHIJAAAA	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) 
	UCHIJAAAA	AntiCheat3{AntiCheat 3 Mod} [AntiCheat 3 Mod] (AntiCheat-3.4.3-1.7.10.jar) 
	UCHIJAAAA	BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5-SaraFix-a1.jar) 
	UCHIJAAAA	Botania{r1.8-248} [Botania] (Botania r1.8-248.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (血魔法 v1.3.3-17 (1.7.10).jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.575} [Forbidden Magic] (Forbidden Magic-1.7.10-0.575.jar) 
	UCHIJAAAA	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3[TFCN].jar) 
	UCHIJAAAA	flammpfeil.slashblade.slasharts{1.7.10 r1} [SlashBlade-SlashArts] ([刀之艺术]SlashBlade-SlashArts-mc1.7.10-r2.jar) 
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 31 / 200; [EntityPlayerMP['jadbaj'/2984153, l='plotworld', x=171.84, y=65.00, z=-473.65](jadbaj at 171.84435997828572,65.0,-473.6491057598298), EntityPlayerMP['ZeroChao'/2984553, l='dy', x=1401.90, y=74.00, z=2219.50](ZeroChao at 1401.9019915400488,74.0,2219.5021465149393), EntityPlayerMP['qian_ying'/3006764, l='zy', x=297.56, y=60.62, z=509.75](qian_ying at 297.5609252591057,60.624514558436964,509.7532635718765), EntityPlayerMP['qing_feng'/3013366, l='plotworld', x=-300.39, y=58.69, z=228.32](qing_feng at -300.3926300640654,58.6875,228.31762709799955), EntityPlayerMP['GSD__WeiAi'/3058204, l='plotworld', x=137.33, y=67.25, z=-508.38](GSD__WeiAi at 137.33266702080994,67.24918707874468,-508.37600045425654), EntityPlayerMP['Alager'/3094781, l='plotworld', x=-218.16, y=67.70, z=975.26](Alager at -218.1564680061716,67.70362554998225,975.25846979623), EntityPlayerMP['Doce_qi'/2991033, l='plotworld', x=-460.56, y=71.00, z=106.53](Doce_qi at -460.55756980337134,71.0,106.53327542467115), EntityPlayerMP['foon'/3124042, l='plotworld', x=-169.60, y=65.00, z=-670.26](foon at -169.60373261411195,65.0,-670.2617002449725), EntityPlayerMP['XUE_BiB'/3011960, l='plotworld', x=381.64, y=65.00, z=-62.91](XUE_BiB at 381.6373411378715,65.0,-62.90877173502692), EntityPlayerMP['H_Herobrine'/3219602, l='plotworld', x=452.60, y=65.00, z=181.42](H_Herobrine at 452.59954919448666,65.0,181.42183258466665), EntityPlayerMP['bimada'/2985168, l='plotworld', x=-224.72, y=65.00, z=-189.43](bimada at -224.72058740852887,65.0,-189.4281971185294), EntityPlayerMP['Yes_RPG'/3228359, l='zy', x=504.34, y=10.00, z=105.30](Yes_RPG at 504.34174880539985,10.0,105.30000001192093), EntityPlayerMP['jingyu'/3280672, l='plotworld', x=-460.32, y=71.00, z=108.30](jingyu at -460.32184365397245,71.0,108.30000001192093), EntityPlayerMP['GB_HH'/3286324, l='plotworld', x=398.24, y=65.60, z=358.60](GB_HH at 398.24373102724934,65.60408037809304,358.60258747239084), EntityPlayerMP['zyj'/3327700, l='world2', x=6054.70, y=140.00, z=-6557.27](zyj at 6054.696827934006,140.0,-6557.273761392779), EntityPlayerMP['MC_Lm'/3331926, l='plotworld', x=-77.15, y=65.00, z=-644.92](MC_Lm at -77.146944870039,65.0,-644.919857452395), EntityPlayerMP['Deceit'/3228511, l='zy', x=491.29, y=25.00, z=93.17](Deceit at 491.29486208010695,25.0,93.16757430673036), EntityPlayerMP['wangling'/3359683, l='plotworld', x=-161.83, y=65.00, z=293.93](wangling at -161.83448723165202,65.0,293.9304380256141), EntityPlayerMP['hexieDD'/3319936, l='plotworld', x=-172.05, y=65.00, z=293.32](hexieDD at -172.0540281966109,65.0,293.322123285703), EntityPlayerMP['wui_yun'/3371586, l='plotworld', x=222.05, y=66.00, z=6.05](wui_yun at 222.04587487693522,66.0,6.050918466870932), EntityPlayerMP['bai'/3377144, l='plotworld', x=-15.76, y=65.00, z=-631.86](bai at -15.75904180544362,65.0,-631.8624643716087), EntityPlayerMP['1138660048'/2984195, l='world2', x=6589.30, y=97.00, z=-1489.61](1138660048 at 6589.300000011921,97.0,-1489.6106607381664), EntityPlayerMP['tcdwyut'/3379224, l='plotworld', x=337.59, y=66.00, z=-438.93](tcdwyut at 337.593518327868,66.0,-438.93328107322435), EntityPlayerMP['MC_SRT'/3071369, l='dy', x=1406.05, y=74.00, z=2220.24](MC_SRT at 1406.047587626412,74.0,2220.236303956137), EntityPlayerMP['96mao'/3324337, l='zy', x=426.88, y=11.00, z=94.31](96mao at 426.88453754763094,11.0,94.30951228047266), EntityPlayerMP['Lo_an'/3278108, l='zy', x=407.49, y=63.00, z=434.79](Lo_an at 407.4881118718084,63.0,434.7858311257941), EntityPlayerMP['Eveccccc'/3430647, l='world2', x=61.91, y=13.00, z=-3467.48](Eveccccc at 61.909833108712505,13.0,-3467.480726350006), EntityPlayerMP['ningchei'/3438062, l='world2', x=535.32, y=38.00, z=-1905.92](ningchei at 535.3200445611056,38.0,-1905.9241799177712), EntityPlayerMP['wtf_GG'/2988502, l='dy', x=1386.88, y=82.00, z=2233.94](wtf_GG at 1386.876214464744,82.0,2233.9396334381295), EntityPlayerMP['laohentai'/3044782, l='plotworld', x=295.67, y=65.00, z=-120.63](laohentai at 295.6682231860085,65.0,-120.63405539263292), EntityPlayerMP['AldnoahLink'/3447323, l='plotworld', x=-310.42, y=65.00, z=89.86](AldnoahLink at -310.41949820131055,65.0,89.85847067593161)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Thermos Version:Thermos Build 58 (ALPHA)**

**Forge Version:1614**

Mods:[mcp, FML, Forge, kimagine, ThaumicTinkerer-preloader, flammpfeil.slashblade.slasharts, balumg, mod_ecru_MapleTree, flammpfeil.slashblade.kamuy, AdvancedSolarPanel, AntiCheat3, BambooMod, Botania, customnpcs, ForbiddenMagic, GraviSuite, IC2, flammpfeil.slashblade, Thaumcraft, ThaumicTinkerer, AWWayofTime, Baubles]

**Comment by Time6628** [comment]
Not thermos. Try Blood Magic.
