### ISSUE TITLE
Crash with some entities and nether portals

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#573]
**Explanation of issue:**
When some entities goes trough nether portals (both nether and overworld chunks loaded), the server crashes. Tested with mana bursts and Shadowbeam focus from Thaumic Tinkerer.

**How to recreate this issue:**
Simplest way: Equip a Shadowbeam focus in a wand, and fire it in direction of the nether portal. Nether chunk must be loaded.

**Thermos Version:**
Thermos 1614 build 58.

```

java.lang.ArithmeticException: / by zero
	at net.minecraft.entity.EntityTrackerEntry.func_73122_a(EntityTrackerEntry.java:166)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:322)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1010)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
```

Crash-report: http://hastebin.com/ekepahojik.sql

**Comment by lurquhar1221** [comment]
Unrelated to Thermos.

**Comment by Eufranio** [comment]
Yeah, I fixed ThaumicTinkerer, nothing to do with Thermos...
