### ISSUE TITLE
Already decorating!

### ISSUE THREAD

**Issue by Eufranio** [CyberdyneCC/Thermos#594]
**Explanation of issue:**
I'm having some issues with my server crashing sometimes, when GalactiCraft tries to decorate their worlds with the following crash-report:

```
java.lang.RuntimeException: Already decorating!!
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.BiomeDecoratorSpace.decorate(BiomeDecoratorSpace.java:24)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.decoratePlanet(ChunkProviderSpace.java:341)
	at micdoodle8.mods.galacticraft.api.prefab.world.gen.ChunkProviderSpace.func_73153_a(ChunkProviderSpace.java:355)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1206)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:77)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
	at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
	at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:212)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323)
	at net.minecraft.world.World.func_72964_e(World.java:799)
	at net.minecraft.world.World.func_72938_d(World.java:794)
	at net.minecraft.world.chunk.Chunk.func_150809_p(Chunk.java:1557)
	at net.minecraft.world.chunk.Chunk.func_150804_b(Chunk.java:1253)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:472)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:745)
```
Full crash-report: http://hastebin.com/exopafuyin.sql

**How to recreate this issue:**
Just run GalactiCraft in a Thermos server and generate some land on a planet. This issue looks like the one that Thermos was having with RTG, but now with GC (and probably other mods...)

Using Thermos 1614 build 58

A good solution would be having an option to disable bukkit-style decorating system in world pre-configured in a config like in Thermos.yml, generating the world just like Forge would...

**Comment by Eufranio** [comment]
???

**Comment by Time6628** [comment]
Not a thermos problem.
