### ISSUE TITLE
Spigot Fix For 1.7.10 Bungeecorf

### ISSUE THREAD

**Issue by Bubble0seven** [CyberdyneCC/Thermos#611]
Wondering where to find this so called spigot fix for running thermos with bungeecord i cannot seem to find it anywhere,

**Comment by Paktosan** [comment]
Use this BungeeCord for Thermos and you are fine: https://github.com/HexagonMC/BungeeCord/releases

**Comment by Bubble0seven** [comment]
Thanks Paktosan that is the one i am using but keep getting the error 

` java.lang.IllegalStateException: Too many channels registered
        at com.google.common.base.Preconditions.checkState(Preconditions.java:145) ~[legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at org.bukkit.craftbukkit.v1_7_R4.entity.CraftPlayer.addChannel(CraftPlayer.java:1068) ~[legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1956) ~[legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:39) ~[legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.PacketPlayInCustomPayload.handle(PacketPlayInCustomPayload.java:51) ~[legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) ~[legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [legacy.jar:git-Spigot-1.7.9-R0.2-208-ge0f2e95]`

**Comment by Eufranio** [comment]
Use Bungeecord from HexagonMC and it should work.

**Comment by Rubbertjuh** [comment]
https://yivesmirror.com/files/fixes/fixes.zip
Includes a fix for that @Bubble0seven replace your spigot .jar

**Comment by Bubble0seven** [comment]
Thanks RubbertJuh
